spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&serverTimezone=UTC
    username: root
    password: votre_mot_de_passe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false